// <auto-generated />
using System;
using BattleHub.Memory.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleHub.Memory.Data.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    partial class MemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("bit");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MatchId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PairId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId1");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryGameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryGameResultPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameResultId");

                    b.ToTable("GameResultPlayers");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MatchId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId1");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryCard", b =>
                {
                    b.HasOne("BattleHub.Memory.Data.Entities.MemoryMatch", "Match")
                        .WithMany("Cards")
                        .HasForeignKey("MatchId1");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryGameResultPlayer", b =>
                {
                    b.HasOne("BattleHub.Memory.Data.Entities.MemoryGameResult", "GameResult")
                        .WithMany("Players")
                        .HasForeignKey("GameResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameResult");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryPlayer", b =>
                {
                    b.HasOne("BattleHub.Memory.Data.Entities.MemoryMatch", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId1");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryGameResult", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("BattleHub.Memory.Data.Entities.MemoryMatch", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
